language: ruby
cache: bundler
sudo: false
bundler_args: --without debug
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.3.1
  - 2.4.0
before_script:
  - jdk_switcher use oraclejdk8

before_install:
  - gem update --system
